server:
  port: 8080

spring:
  application:
    name: ph-neutralizer

  datasource:
    url: jdbc:sqlite:hardware.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: VARCHAR

        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true

        event:
          merge:
            entity_copy_observer: disallow

  sql:
    init:
      mode: never

# Modbus Configuration
modbus:
  connections:
    - name: neutralizer
      host: rtu:///dev/ttyACM0:38400
      timeout: 2000
      parity: none
      stop-bits: 1
      data-bits: 8

# Neutralizer Hardware Configuration
neutralizer:
  connection-name: neutralizer
  slave-id: 1

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Logging
logging:
  level:
    "[bio.altar.phneutralizer]": DEBUG
    root: INFO
  event:
    path: ./logs
    retention-days: 30
    archive-after-days: 7
    enabled: true
    scheduled: true


# B2 Cloud Backup
b2:
  enabled: ${B2_ENABLED:false}
  application-key-id: ${B2_KEY_ID:}
  application-key: ${B2_KEY:}
  default-bucket-name: ${B2_BUCKET:ph-neutralizer-backup}

anode:
  security:
    env-local-jwt: true
    login-url: /neutralizer
    post-logout-url: /
    allowedPatterns:
      - /api/users/login
      - /neutralizer
      - /index.html
      - /assets/**
      - /api/events/subscribe
      - /favicon.ico